baseURL = 'https://hookwrgms.github.io'
languageCode = 'en-us'
title = "Hook's Research Log"
theme = 'hyde'

[params]
  description = "Research notes, syntheses, and explorations"
  themeColor = "theme-base-08"

[menu]
  [[menu.main]]
    name = 'Posts'
    url = '/posts/'
    weight = 10